### ISSUE TITLE
I added a button to the grid in the tool bar  and I want  to reload the grid on clicking a button with some filtering condition, is there a way to achieve this. Thank you

### ISSUE THREAD

**Issue by satyachappidi** [robinvanderknaap/MvcJqGrid#41]

**Comment by farrukhsubhani** [comment]
Yes there is a way to do this, you need to do following on click event of new button
- read filters and update postData with filters
- call grid reload method

If you set filters before relaod method, grid will pickup filters and bring filtered data back.

**Comment by daanl** [comment]
This has nothing to do with our plugin, please ask these questions on stackoverflow.
