### ISSUE TITLE
Refresh or Flush the grid

### ISSUE THREAD

**Issue by mbraunwart** [robinvanderknaap/MvcJqGrid#52]
Hello! I am having some kind of weird caching issue with the grid, where even though I am verifying the data coming back from the server, the grid still displays the previous data. Even if a status changes and the line item shows up in the new correct status, it still displays the cached data. On my html layout, I am using these meta tags in the header 
	<meta http-equiv="Pragma" content="no-cache"/>
	<meta http-equiv="Expires" content="-1" />
But that doesn't seem to help the caching within the grid. Is there some way to flush the data in the grid before retrieving data from the server?

**Comment by mbraunwart** [comment]
<- meta http-equiv="Pragma" content="no-cache"/>
	<- meta http-equiv="Expires" content="-1" />

**Comment by mbraunwart** [comment]
I should also state that most users are using IE7-IE11. It appears to be happening in any IE browser. I cannot replicate in Chrome or Firefox.

**Comment by bunny1985** [comment]
weel this is not really Crossword Issue. This is Html Caching Issue. 
It's not connected with crossword implementation at all.
First thing you can do is to change headers in your response. 
If you don't know whata I'm talking about just google it. (no cache cache limit 0 html disable cqache osr so on ) 

Second chance ( and you can sauy it's hack ) is to change link :)
You can force browser to allways get new version by calling to address with changed param
for example
js/cw.js?v1

js/cw.js?v2
.....
js/cw.js?v2

you can also change v2 to current timestamp to force allways refresh.
